spring:
  application:
    name: Producer
  threads:
    virtual:
      enabled: true

server:
  port: 8080

redis:
  host: localhost
  port: 6379
  stream:
    name: tdrive:stream
    group: tdrive:group

tdrive-dataset:
  path: /home/lethiyun02/
